### ISSUE TITLE
Incorrect API response for noindex

### ISSUE THREAD

**Issue by rizkysyazuli** [parfaitementweb/statamic-fast-seo#1]
I see the `nofollow` and `noarchive` in Statamic's REST API response. But I don't see `noindex`.

Yet, I see this weird `d` field as shown below. Which changes to whatever i set noindex. And It's definitely not one of my custom fields.

<img width="268" alt="Jepretan Layar 2021-10-20 pukul 14 59 20" src="https://user-images.githubusercontent.com/152221/138052621-3ff16c89-fd13-478f-a6f2-4ca7c72453ff.png">

<img width="879" alt="Jepretan Layar 2021-10-20 pukul 15 04 49" src="https://user-images.githubusercontent.com/152221/138053148-e2da7507-7e4e-4e06-ba63-a6ecb2516b2a.png">

**Comment by AlexisSerneels** [comment]
Thank you. It has been fixed in latest release.
